name: ci
on:
  push:
    branches:
      - master
      - ci/cd

jobs:
  build:
    name: Build Image and Push to ACR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Login to ACR
        uses: aliyun/acr-login@v1
        with:
          login-server: https://registry.cn-shenzhen.aliyuncs.com
          region-id: cn-shenzhen
          username: '${{ secrets.ACR_USERNAME }}'
          password: '${{ secrets.ACR_PASSWORD }}'

      - name: Build and push image
        run: |
          docker build -t $IMG_REPO/$IMG_NAME:$IMG_TAG .
          docker push $IMG_REPO/$IMG_NAME:$IMG_TAG

env:
  IMG_REPO: registry.cn-shenzhen.aliyuncs.com/image-vt
  IMG_NAME: cc-my-next-blog
  IMG_TAG: latest
